---
- name: Fill configuration template
  ansible.builtin.template:
    src: "app-config.yaml"
    dest: "{{ app_fragments }}/00-grizzlaxy.yaml"
    mode: "0600"

- name: Consolidate all configuration
  ansible.builtin.assemble:
    src: "{{ app_fragments }}"
    dest: "{{ app_config }}"
    mode: "0600"

- name: Create cert directory
  ansible.builtin.file:
    path: "{{ app_config_dir }}/cert"
    state: directory
    mode: "0700"

- name: Copy certificate
  ansible.builtin.copy:
    content: "{{ app_ssl_cert }}"
    dest: "{{ app_config_dir }}/cert/cert.pem"
    mode: "0600"

- name: Copy certificate key
  ansible.builtin.copy:
    content: "{{ app_ssl_key }}"
    dest: "{{ app_config_dir }}/cert/cert-key.pem"
    mode: "0600"

- name: Fill service definition template
  become: true
  ansible.builtin.template:
    src: "grizzlaxy.service"
    dest: "/etc/systemd/system/{{ app_name }}-web.service"
