---
- name: Restore permissions the config directory
  become: true
  ansible.builtin.file:
    path: "{{ app_config_dir }}"
    state: directory
    recurse: true
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Restore permissions the code directory
  become: true
  ansible.builtin.file:
    path: "{{ app_code_dir }}"
    state: directory
    recurse: true
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Restore permissions the conda directory
  become: true
  ansible.builtin.file:
    path: "{{ conda_base }}"
    state: directory
    recurse: true
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Restart service
  become: true
  ansible.builtin.systemd:
    name: "{{ app_name }}-web.service"
    daemon_reload: true
    state: restarted
