---
- name: Create the app directory
  become: true
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory
    mode: "0755"

- name: Create the data directory
  become: true
  ansible.builtin.file:
    path: "{{ app_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ app_user }}"

- name: Create the config directory
  ansible.builtin.file:
    path: "{{ app_config_dir }}"
    state: directory
    mode: "0755"

- name: Clear fragments directory
  ansible.builtin.file:
    path: "{{ app_fragments }}"
    state: absent

- name: Create fragments directory
  ansible.builtin.file:
    path: "{{ app_fragments }}"
    state: directory
    mode: "0755"
